
import Head from 'next/head'
import Login from './app/pages/login/login'
import Noticies from '../pages/app/pages/policies/Notices'
import Policies from './app/pages/policies/Policies'
import Terms from './app/pages/policies/Terms'
import CustomNavBar from './app/components/CustomNavbar'
import SignUp from './app/pages/S/SignUp'
import NewProyect from './app/pages/customProyects/newProyect'
import Proyect from './app/pages/Proyectos/Proyect'
import ViewProyect from './app/pages/customProyects/ViewProyect'
import styles from '../styles/Home.module.css'
import Recursos from './app/pages/customProyects/Recursos'
import { useState } from 'react'
import DetalleProyecto from './app/pages/customProyects/DetalleProyecto'
import MenuPrincipal from './app/pages/customProyects/MenuPrincipal'


// const [ sesion, setSesion ] = useState(false);

// const [credenciales, setCredenciales] = useState(initialCredencials);

// const initialCredencials = {
//   user:'',
//   password: '',
// }


const Home =()=> {
  

  
  return (
    <div>
      <Head>
        <title>Calculadora Lunave</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      
        <div>
    
    <Login/>
        {/* <Login credenciales = {credenciales} sesion = {sesion}/> */}
        {/*
        <Noticies/>
        <Policies/>
        <Terms/>*/}
        </div>
      
           
  </div>
  )
}

export default Home;